services:
  mysql:
    build: ./mysql/
    image: gilberto9172/play-ground:latest
    container_name: play-ground
    volumes:
      - play_ground_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: study
    ports:
      - '9172:3306'
    restart: always
    platform: linux/amd64
    networks:
      - gilbert-local-network

  redis:
    image: redis:7.4.1
    container_name: redis-container
    privileged: true
    ports:
      - "6380:6380"
    volumes:
      - play_ground_redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes" ]
    networks:
      - gilbert-local-network


networks:
  gilbert-local-network:

volumes:
  play_ground_mysql_data:
  play_ground_redis_data:
